# how long after login a player will receive the first message (in seconds)
timeAfterLogin: 15
# if the user has no paid perks
byPlaytime:
  # < the number in minutes
  10:
    groupSpecificMessages:
    - 'msg 1'
    interval: 200
    # ratios of announcement types (positive numbers, can sum to anything < 2.1 billion)
    promotionRatio: 0
    groupSpecificRatio: 0
    informationRatio: 100
  1440:
    groupSpecificMessages:
    - 'msg 1'
    interval: 300
    promotionRatio: 0
    groupSpecificRatio: 10
    informationRatio: 90
  aboveHighestTime:
    groupSpecificMessages:
    - 'msg 1'
    interval: 300
    promotionRatio: 0
    groupSpecificRatio: 10
    informationRatio: 90
# players will receive messages promoting the perks they don't have
promotionMessages:
  # propotion of messages which will list multiple items
  listProportion: 0.85
  groups:
    fly:
      # relative frequency of this perk being promoted
      frequency: 100
      # short description which will appear in comma separated lists
      list:
      - '/fly'
      - '/fly'
      messages:
      - 'msg 1'
    unlimitedhomes:
      frequency: 100
      list:
      - '/fly'
      - '/fly'
      messages:
      - 'msg 1'
    nick:
      frequency: 50
      list:
      - '/fly'
      - '/fly'
      messages:
      - 'msg 1'
  # (listTemplate1)(item 1)(listTemplate2)(item 2)(listTemplate3)(item 3)(listTemplate4)
  listTemplate1: ''
  listTemplate2: ', '
  listTemplate3: ', and '
  listTemplate4: ' at website'
informationMessages:
- 'info 1'
- 'info 2'